apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSProvider 
metadata:
  name: gcp-dns-provider
  labels:
    app.kubernetes.io/name: gcp-dns-provider
  annotations:
    dns.gardener.cloud/class: garden
  namespace: gcp-gateway
spec:
  type: google-clouddns
  secretRef:
    name: gcp-dns-sa-secret
    namespace: gcp-gateway
  domains:
    include:
      - '*.kyma.<yourdomainhere>'
